// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeGridConnection(arg1) {
  return window['go']['main']['App']['AnalyzeGridConnection'](arg1);
}

export function AnalyzeGridDemand(arg1) {
  return window['go']['main']['App']['AnalyzeGridDemand'](arg1);
}

export function AnalyzeSolarResource(arg1) {
  return window['go']['main']['App']['AnalyzeSolarResource'](arg1);
}

export function AnalyzeSolarTerrain(arg1) {
  return window['go']['main']['App']['AnalyzeSolarTerrain'](arg1);
}

export function AnalyzeUsableGround(arg1) {
  return window['go']['main']['App']['AnalyzeUsableGround'](arg1);
}

export function AnalyzeWindResource(arg1) {
  return window['go']['main']['App']['AnalyzeWindResource'](arg1);
}

export function CancelRun() {
  return window['go']['main']['App']['CancelRun']();
}

export function ClearAvatar() {
  return window['go']['main']['App']['ClearAvatar']();
}

export function CurrentUser() {
  return window['go']['main']['App']['CurrentUser']();
}

export function DisconnectGridStore() {
  return window['go']['main']['App']['DisconnectGridStore']();
}

export function ExportResultFile(arg1, arg2) {
  return window['go']['main']['App']['ExportResultFile'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBootLogs() {
  return window['go']['main']['App']['GetBootLogs']();
}

export function GridConcessions() {
  return window['go']['main']['App']['GridConcessions']();
}

export function GridDemandReach(arg1) {
  return window['go']['main']['App']['GridDemandReach'](arg1);
}

export function GridNetwork() {
  return window['go']['main']['App']['GridNetwork']();
}

export function GridPlants() {
  return window['go']['main']['App']['GridPlants']();
}

export function GridStoreConnection() {
  return window['go']['main']['App']['GridStoreConnection']();
}

export function GridTownDemand() {
  return window['go']['main']['App']['GridTownDemand']();
}

export function InspectGridStore() {
  return window['go']['main']['App']['InspectGridStore']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function ParameterDefaults() {
  return window['go']['main']['App']['ParameterDefaults']();
}

export function ParseGridStoreURL(arg1) {
  return window['go']['main']['App']['ParseGridStoreURL'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function RevealInFileManager(arg1) {
  return window['go']['main']['App']['RevealInFileManager'](arg1);
}

export function RevealMainWindow() {
  return window['go']['main']['App']['RevealMainWindow']();
}

export function SaveProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2, arg3);
}

export function SaveTextFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2, arg3, arg4);
}

export function SetAvatar(arg1) {
  return window['go']['main']['App']['SetAvatar'](arg1);
}

export function SetGridStore(arg1) {
  return window['go']['main']['App']['SetGridStore'](arg1);
}

export function SetGridStoreConnection(arg1) {
  return window['go']['main']['App']['SetGridStoreConnection'](arg1);
}

export function SetProjectDirty(arg1) {
  return window['go']['main']['App']['SetProjectDirty'](arg1);
}

export function StoreBoundary(arg1) {
  return window['go']['main']['App']['StoreBoundary'](arg1);
}

export function StoreBoundaryList() {
  return window['go']['main']['App']['StoreBoundaryList']();
}

export function TestGridStore(arg1) {
  return window['go']['main']['App']['TestGridStore'](arg1);
}

export function UpdateDisplayName(arg1) {
  return window['go']['main']['App']['UpdateDisplayName'](arg1);
}

export function WindField(arg1, arg2) {
  return window['go']['main']['App']['WindField'](arg1, arg2);
}

export function WorldBoundary(arg1, arg2, arg3) {
  return window['go']['main']['App']['WorldBoundary'](arg1, arg2, arg3);
}

export function WorldCountries() {
  return window['go']['main']['App']['WorldCountries']();
}

export function WorldLevels(arg1) {
  return window['go']['main']['App']['WorldLevels'](arg1);
}

export function WorldPlaces(arg1, arg2) {
  return window['go']['main']['App']['WorldPlaces'](arg1, arg2);
}
