// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {grid} from '../models';
import {energy} from '../models';
import {store} from '../models';
import {main} from '../models';
import {weather} from '../models';

export function AnalyzeGridConnection(arg1:grid.ConnectionRequest):Promise<grid.ConnectionAnalysis>;

export function AnalyzeGridDemand(arg1:grid.DemandRequest):Promise<grid.DemandAnalysis>;

export function AnalyzeSolarResource(arg1:energy.SolarRequest):Promise<energy.SolarAnalysis>;

export function AnalyzeSolarTerrain(arg1:energy.SolarTerrainRequest):Promise<energy.SolarTerrainAnalysis>;

export function AnalyzeWindResource(arg1:energy.WindRequest):Promise<energy.WindAnalysis>;

export function CancelRun():Promise<boolean>;

export function ClearAvatar():Promise<store.User>;

export function CurrentUser():Promise<store.User>;

export function ExportResultFile(arg1:string,arg2:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetBootLogs():Promise<Array<string>>;

export function GridNetwork():Promise<grid.NetworkLayer>;

export function GridPlants():Promise<grid.PlantsLayer>;

export function InspectGridStore():Promise<grid.StoreReport>;

export function Login(arg1:string,arg2:string):Promise<store.User>;

export function Logout():Promise<void>;

export function OpenProject(arg1:string):Promise<main.OpenedProject>;

export function ParameterDefaults():Promise<energy.ParameterDefaults>;

export function Ping():Promise<main.SidecarStatus>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<store.User>;

export function RevealInFileManager(arg1:string):Promise<void>;

export function RevealMainWindow():Promise<void>;

export function SaveProject(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function SaveTextFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SetAvatar(arg1:string):Promise<store.User>;

export function SetGridStore(arg1:string):Promise<grid.StoreReport>;

export function SetProjectDirty(arg1:boolean):Promise<void>;

export function UpdateDisplayName(arg1:string):Promise<store.User>;

export function WindField(arg1:number):Promise<weather.WindField>;
